FROM python:3.12-slim

RUN apt-get update \
  && apt-get install -y --no-install-recommends libxml2-utils \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY server/validator.py /app/validator.py
COPY schemas/r07 /schemas
COPY schemas/r08 /schemas

EXPOSE 8081
CMD ["python", "/app/validator.py"]
